run_logged $OMARI_INSTALL/config/config.sh
run_logged $OMARI_INSTALL/config/user-dirs.sh
run_logged $OMARI_INSTALL/config/theme.sh
run_logged $OMARI_INSTALL/config/branding.sh
run_logged $OMARI_INSTALL/config/git.sh
run_logged $OMARI_INSTALL/config/ssh-flakiness.sh
run_logged $OMARI_INSTALL/config/increase-file-watchers.sh
run_logged $OMARI_INSTALL/config/detect-keyboard-layout.sh
run_logged $OMARI_INSTALL/config/mise-work.sh
run_logged $OMARI_INSTALL/config/mimetypes.sh
run_logged $OMARI_INSTALL/config/docker.sh
run_logged $OMARI_INSTALL/config/localdb.sh
run_logged $OMARI_INSTALL/config/walker-elephant.sh
run_logged $OMARI_INSTALL/config/mask-services.sh
run_logged $OMARI_INSTALL/config/keyring.sh
run_logged $OMARI_INSTALL/config/fast-shutdown.sh
run_logged $OMARI_INSTALL/config/sudoless-asdcontrol.sh

run_logged $OMARI_INSTALL/config/hardware/network.sh
run_logged $OMARI_INSTALL/config/hardware/fix-fkeys.sh